Update VerisonLinkWorkFlow.yml

diff --git a/.github/workflows/VerisonLinkWorkFlow.yml b/.github/workflows/VerisonLinkWorkFlow.yml
--- a/.github/workflows/VerisonLinkWorkFlow.yml
+++ b/.github/workflows/VerisonLinkWorkFlow.yml
@@ -45,7 +45,7 @@ jobs:
       uses: actions/checkout@v1
     - name: Build the Docker image
       run: |
-        docker build -t lalitku/hybrid-comp-image-two:1.0.0-${{ github.run_number }} --label build.url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} .
+        docker build -t lalitku/hybrid-comp-image-two:2.0.0-${{ github.run_number }} --label build.url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} .
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx
@@ -57,7 +57,7 @@ jobs:
         password: Lalit/2698
     - name: Push
       run: |
-          docker push lalitku/hybrid-comp-image-two:1.0.0-${{ github.run_number }}
+          docker push lalitku/hybrid-comp-image-two:2.0.0-${{ github.run_number }}
   ucd:
     needs: [build, scan]
     runs-on: self-hosted
@@ -65,37 +65,37 @@ jobs:
     steps:
     - name: Import Component Into UCD
       run: |
-        curl --insecure --request PUT 'https://10.134.119.198:8443/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"component": "HybridApp2Comp1","properties": {"version": "1.0.0-${{ github.run_number }}","description": ""}}'
+        curl --insecure --request PUT 'https://10.134.119.198:8443/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"component": "HybridApp2Comp2","properties": {"version": "2.0.0-${{ github.run_number }}","description": ""}}'
     - name: Install jq
       run: |
         wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
         chmod +x jq
         sudo mv jq /usr/local/bin/
-#     - name: Run curl with loop and timeout
-#       id: find_component_version
-#       run: |
-#         timeout_duration=600  # Set the timeout duration in seconds (e.g., 300 seconds = 5 minutes)
-#         target_version_name="1.0.0-${{ github.run_number }}"  # Replace with the specific version name you are looking for
+    - name: Run curl with loop and timeout
+      id: find_component_version
+      run: |
+        timeout_duration=600  # Set the timeout duration in seconds (e.g., 300 seconds = 5 minutes)
+        target_version_name="2.0.0-${{ github.run_number }}"  # Replace with the specific version name you are looking for
 
-#         end_time=$((SECONDS + timeout_duration))
+        end_time=$((SECONDS + timeout_duration))
 
-#         while [ $SECONDS -lt $end_time ]; do
-#           response=$(curl --insecure  --request GET 'https://10.134.119.198:8443/cli/component/versions?component=HybridApp2Comp1' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=')
-#           version_names=$(echo "$response" | jq -r '.[].name')
+        while [ $SECONDS -lt $end_time ]; do
+          response=$(curl --insecure  --request GET 'https://10.134.119.198:8443/cli/component/versions?component=HybridApp2Comp2' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=')
+          version_names=$(echo "$response" | jq -r '.[].name')
 
-#           if echo "$version_names" | grep -q "$target_version_name"; then
-#             echo "Found version with name: $target_version_name"
-#             echo "$response"  # Print the full response for the matching version (optional)
-#             break
-#           fi
+          if echo "$version_names" | grep -q "$target_version_name"; then
+            echo "Found version with name: $target_version_name"
+            echo "$response"  # Print the full response for the matching version (optional)
+            break
+          fi
 
-#           sleep 10  # Adjust the sleep duration (in seconds) between each curl request
-#         done
+          sleep 10  # Adjust the sleep duration (in seconds) between each curl request
+        done
 
-#         if [ $SECONDS -ge $end_time ]; then
-#           echo "Timeout reached. Version with name $target_version_name not found."
-#           exit 1
-#         fi
+        if [ $SECONDS -ge $end_time ]; then
+          echo "Timeout reached. Version with name $target_version_name not found."
+          exit 1
+        fi
     - name: Create Snapshot
       run: |
-        curl --insecure --request PUT 'https://10.134.119.198:8443/cli/snapshot/createSnapshot' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"name": RC-${{ github.run_number }},"application": "Hybrid App 2","description": "Some snapshot","versions": [{"HybridApp2Comp1": "latest"}]}'
+        curl --insecure --request PUT 'https://10.134.119.198:8443/cli/snapshot/createSnapshot' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"name": RC-${{ github.run_number }},"application": "Hybrid App 2","description": "Some snapshot","versions": [{"HybridApp2Comp2": "2.0.0-${{ github.run_number }}"}]}'
